### ISSUE TITLE
Vertaisarviointi Tiralabra

### ISSUE THREAD

**Issue by Triviaali** [bensku/skripty#8]
En saanut projektia käynnistymään javalla ja kahdella eri gradlen versiolla joten luovutin. Asennusohjeet olisivat hyvä lisä. Katsoin kuitenkin koodia ja se on erittäin selkeätä ja hyvin kommentoitu. Koodi on myös jaoteltu loogisesti omiin kansioihin ja sitä on helppo seurata. Testejä en ajanut, mutta codecovin perusteella testikattavuutta voisi parantaa vielä hieman.

Erittain hyvaa tyota!

**Comment by bensku** [comment]
Koodin ajaminen on tosiaan aika hankalaa tällä hetkellä, eikä myöskään ohjetta skriptauskielen *käyttöön* ole. Teen jonkinlaisen käyttöohjeen ennen seuraavaa vertaisarviota.
